### ISSUE TITLE
Required parameters

### ISSUE THREAD

**Issue by dsoprea** [pborman/getopt#3]
After looking through the documentation, source code, and spending a fair amount of time trying to find anything useful on Google, I'm still unsure how to bring required arguments from the command-line along with optional flags/values.

I'm using `os.Args`. The flags/values seem to be ignored if they're provided last but obviously used as the initial arguments if provided first. How are we supposed to do this?

**Comment by norman-abramovitz** [comment]
This package does not have reasonable builtin support for required parameters or subcommands.   You need to remove the parameter from the Args slice and then call Parse or GetOpt again to continue parsing the cli arguments.   I have not tried myself yet, but I believe you can look at the State and make some decisions off of that.   It needs this enhancement given that it deviated from the original BSD getopt design on interface usage.   As best as I can tell,  the documentation for this package is https://godoc.org/code.google.com/p/getopt.   Some more real world examples in the documentation would really help here.
