### ISSUE TITLE
Simple README update

### ISSUE THREAD

**Issue by tractaylor** [pborman/getopt#9]
While reading over the documentation, I found a simple error.  I found a sentence that had "... and and...".  I believe the text should say "...a and b..."
In vim, its line 168 in the readme file.  And I have attached a sceen shot as well.  I will be opening a pull request

<img width="942" alt="screen shot 2018-05-29 at 9 57 16 pm" src="https://user-images.githubusercontent.com/5148702/40696491-b666102c-638b-11e8-8d58-2b62b767859c.png">

Also, this is my first time to contribute to this project and I did create a Contributing License Agreement, but not sure what to do with it.

thanks!

**Comment by j0hnwhyte** [comment]
I might add that the README needs some fixes in the repository (`/v2` in the `go get` URL doesn't work) and the example code, which I can't make any proper sense of, for example the flags are declared outside a block, the syntax for var is wrong and they aren't actually used. A more friendly example could help a lot newcomers.
